/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openocf_ocfresources_InfoDevice */

#ifndef _Included_openocf_ocfresources_InfoDevice
#define _Included_openocf_ocfresources_InfoDevice
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
