/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openocf_engine_OCFClientServerSP */

#ifndef _Included_openocf_engine_OCFClientServerSP
#define _Included_openocf_engine_OCFClientServerSP
#ifdef __cplusplus
extern "C" {
#endif
#undef openocf_engine_OCFClientServerSP_CLIENT
#define openocf_engine_OCFClientServerSP_CLIENT 0L
#undef openocf_engine_OCFClientServerSP_SERVER
#define openocf_engine_OCFClientServerSP_SERVER 1L
#undef openocf_engine_OCFClientServerSP_CLIENT_SERVER
#define openocf_engine_OCFClientServerSP_CLIENT_SERVER 2L
#undef openocf_engine_OCFClientServerSP_GATEWAY
#define openocf_engine_OCFClientServerSP_GATEWAY 3L
#undef openocf_engine_OCFClientServerSP_QOS_LOW
#define openocf_engine_OCFClientServerSP_QOS_LOW 0L
#undef openocf_engine_OCFClientServerSP_QOS_MEDIUM
#define openocf_engine_OCFClientServerSP_QOS_MEDIUM 1L
#undef openocf_engine_OCFClientServerSP_QOS_HIGH
#define openocf_engine_OCFClientServerSP_QOS_HIGH 2L
#undef openocf_engine_OCFClientServerSP_QOS_NA
#define openocf_engine_OCFClientServerSP_QOS_NA 3L
#ifdef __cplusplus
}
#endif
#endif
