/* server.h */
#ifndef SERVER_H_
#define SERVER_H_

#include "ocstack.h"
#include "logger.h"
#include "ocpayload.h"

/* Platform Descriptor: OCPlatformInfo
 * This structure describes the platform properties. All non-Null properties will be
 * included in a platform discovery request. */
OCPlatformInfo platform_info =
  {
    .platformID			= "myPlatformID",
    .manufacturerName		= "myName",
    .manufacturerUrl		= "myManufacturerUrl",
    .modelNumber			= "myModelNumber",
    .dateOfManufacture		= "myDateOfManufacture",
    .platformVersion		= "myPlatformVersion",
    .operatingSystemVersion	= "myOS",
    .hardwareVersion		= "myHardwareVersion",
    .firmwareVersion		= "myFirmwareVersion",
    .supportUrl			= "mySupportUrl",
    .systemTime			= "2015-05-15T11.04"
  };

/* Device Descriptor: OCDeviceInfo
 * This structure is expected as input for device properties.
 * device name is mandatory and expected from the application.
 * device id of type UUID will be generated by the stack. */
OCDeviceInfo deviceInfo =
  {
    .deviceName = "myDeviceName",
    /* OCStringLL *types; */
    .specVersion = "myDeviceSpecVersion", /* device specification version */
    .dataModleVersion = "myDeviceModleVersion"
  };

/* const char *deviceUUID = "myDeviceUUID"; */
/* const char *version = "myVersion"; */


static int g_observe_notify_type = 3;

#endif

