/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openocf_Service */

#ifndef _Included_openocf_Service
#define _Included_openocf_Service
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     openocf_Service
 * Method:    configuration
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_openocf_Service_configuration
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
