= security

Components:

* Persistent store
* Security resources (oic/sec/acl etc.)
* Security Resource Manager
* Policy Engine
* OnBoarding Tool
* Device Ownership Tranfer Service (DOXS)


=== abbrevs & acronynms

* AMS - ACL Mgmt Service

* SRM - secure resource manager

* psm - persistent storage manager

* doxm - device ownership transfer manager/method

=== security resources

URLs and types (OCF 1.3 draft, summary at p 120-)

oic/sec/acl	    oic.r.acl	p. 143
  oic.r.ace
  oic.sec.crudntype
  etc.

oic/sec/acl2   	    oic.r.acl2  p. 148
		    oic.sec.acl2
		    oic.sec.ace2
		    oic.sec.ace2.resource-ref
		    oic.sec.conntype
		    oic.sec.roletype
		    etc.

oic/sec/amacl	    oic.r.amacl	Access Manager ACL p. 153

oic/sec/sacl	    oic.r.sacl	Secure ACL p. 153
		    oic.sec.sigtype

oic/sec/doxm	    oic.r.doxm
		    oic.sec.doxmtype
oic/sec/didtype	    oic.sec.didtype?  a property resource on doxm

oic/sec/cred	    oic.r.cred	      p. 128
  credential usage (p. 137)
		    oic.sec.cred.trustca
		    oic.sec.cred.cert
		    etc.

	    oic.sec.pubdatatype	p. 133
	    oic.sec.privdatatype
	    oic.sec.optdatatype
	    oic.sec.roletype	p. 135

  Credential Refresh Method p. 136
	    oic.sec.crm
	    oic.sec.crm.pro
	    etc.

oic/sec/crl	oic.r.crl	Certificate Revocation List, p. 141


oic/sec/pstat	    oic.r.pstat	Provisioning Status, p. 155
		    oic.sec.dostype	     Device Onboarding State, p. 159
		    oic.sec.dpmtype	     Device Provisioning Mode p. 162
		    oic.sec.pomtype	     Provisioning Operation Mode, p. 162

oic/sec/csr	    oic.r.csr		     Certificate Signing Request, p. 163

oic.r.roles	    oic.r.roles		     p. 164


=== Principles of Operation

==== alcresource implementation

e.g. aclresource.c

* lifecycle routines: init, start, stop, etc. calloc/free, etc.

* conversion routines: internal structs to and from cbor

* ace database mgmt - create, add, delete ACEs in db

* ocf request query string parsing routines

* stats: sec resource count, etc

* comparison ops: is_same_ace etc.


==== Initialization

(Ignoring TCP here)

ocstack.c/OCInit
  ocstack.c/OCInit1
    ocstack.c/OCInit2 
      ocstack.c/OCInitializeInternal

BEGIN OCInitializeInternal
* some housekeeping...
* InitializeScheduleResourceList
* CAInitialize
* OCSelectNetwork(transportType));
* CARegisterNetworkMonitorHandler
* depending on mode (client, server, both):
** client: CARegisterHandler(HandleCARequests, HandleCAResponses, HandleCAErrorResponse);
*** CAStartDiscoveryServer()
** server: SRMRegisterHandler(HandleCARequests, HandleCAResponses, HandleCAErrorResponse);
*** CAStartListeningServer()
** client-server or gateway:
*** SRMRegisterHandler(HandleCARequests, HandleCAResponses, HandleCAErrorResponse);
*** CAStartListeningServer()
*** CAStartDiscoveryServer()

At this point the stackState is OC_STACK_INITIALIZED.

Next: initialize resources:

* if mode != client
** initResources()
start by creating resources:
*** OCCreateResource for /oic/ad ("PRESENCE" resource)
***    OCCreateResource always indirectly calls presence.c/SendPresenceNotification
*** src/sec/secureresourcemanager.c:SRMInitSecureResources()
**** src/sec/resourcemanager.c:InitSecureResources( )
***** src/sec/doxmresource.c:InitDoxmResource()
***** src/sec/resourcemanager.c:InitPstatResource()
***** src/sec/aclresource.c:InitACLResource()
***** src/sec/credresource.c:InitCredResource()
if __WITH_DTLS__ or __WITH_TLS__
***** src/sec/crlresource.c:InitCRLResource()
***** src/sec/csrresource.c:InitCSRResource()
***** src/sec/rolesresource.c:InitRolesResource()
endif
***** src/sec/amaclresource.c:InitAmaclResource()

*** CAregisterPskCredentialsHandler(GetDtlsPskCredentials)
*** CAregisterPkixInfoHandler(GetPkixInfo);
*** CAregisterGetCredentialTypesHandler(InitCipherSuiteList);
now do mandatory non-security resources
*** OCCreateResource for /oic/res (discovery resource?)
*** CreateResetProfile()
*** OCCreateResource for /oic/d (DEVICE resource)
*** OCCreateResource for /oic/p (PLATFORM resource)
*** OCCreateResource for /introspection
*** OCCreateResource for /introspection/payload
then initialize device and platform props:
*** InitializeDeviceProperties()
*** OICGetPlatformUuid
*** OCSetPropertyValue(PAYLOAD_TYPE_PLATFORM, OC_RSRVD_PLATFORM_ID, uuidString) (Overridable by app)
end initResources

* if routing:
** RMSetStackMode(mode);
** if (OC_GATEWAY == myStackMode) RMInitialize()
END OCInitializeInternal




=== TODO

* extract persistent storage mgr from secureresourcemanager

* this will make it possible to remove the dependency of ocstack.h on the latter+

* security_internals.h - why isn't this stuff distributed to the resource headers?
