##
# CA build script
##

Import('env')

ca_os = env.get('TARGET_OS')
src_dir = env.get('SRC_DIR')
root_dir = './../'

ca_common_path = root_dir + 'common/'
ca_common_src_path = ca_common_path + 'src/'

ca_common_src = [ca_common_src_path + 'uarraylist.c'
		,ca_common_src_path + 'ulinklist.c'
		,ca_common_src_path + 'uqueue.c'
		,ca_common_src_path + 'caremotehandler.c']

if env.get('PTHREAD_LIB') == 'pthread':
	platform_src = [
	    ca_common_src_path + 'cathreadpool_pthreads.c',
	    ca_common_src_path + 'camutex_pthreads.c'
	    ]
else:
        platform_src = [
	    ca_common_src_path + 'camutex_noop.c'
	]

env.AppendUnique(CA_SRC = ca_common_src)
env.AppendUnique(CA_SRC = platform_src)
