#******************************************************************
#
# Copyright 2014 Intel Mobile Communications GmbH All Rights Reserved.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Import('test_env')
import os
import os.path
import build.utils

test_env = test_env.Clone()

target_os = test_env.get('TARGET_OS')

######################################################################
# Build flags
######################################################################
test_env.PrependUnique(CPPPATH = [
		'#resource/csdk/security',
		'#resource/csdk/security/ocsecurity',
		'#resource/csdk/provisioning',
		'#resource/csdk/logger',
		'#resource/csdk/cbor',
		'#resource/c_common',
		'#resource/csdk/stack',
		'#resource/csdk/stack/internal',  #FIXME: this is private
		'#resource/csdk/connectivity/api',
		'#resource/csdk/connectivity/external/inc',
		'#resource/csdk/cjson'
		])
#		'#resource/oc_logger/include'
#		'../../stack/internal',

test_env.PrependUnique(LIBS = ['chibity',
                               'ocsrm',
                               'ocpmapi',
                               'connectivity_abstraction',
                               'coap',
                               'c_common'])

# if target_os != 'darwin':
#         test_env.PrependUnique(LIBS = ['uuid'])

test_env.AppendUnique(LIBPATH = [test_env.get('INSTALL_SYSROOT') + '/lib',
			         test_env.get('BUILD_SYSROOT') + '/provisioning',
 			         test_env.get('BUILD_SYSROOT') + '/c_common',
  			         test_env.get('BUILD_SYSROOT') + '/connectivity/core',
 			         test_env.get('BUILD_SYSROOT') + '/connectivity/coap'])
 # 			         test_env.get('BUILD_SYSROOT') + '/logger',

# test_env.PrependUnique(LIBS = ['csdk'])

if test_env.get('SECURED'):
    test_env.PrependUnique(LIBS = ['ocsrm'])
    test_env.PrependUnique(LIBPATH = [test_env.get('BUILD_SYSROOT') + '/security'])
    test_env.PrependUnique(LIBS = ['ocpmapi'])
    test_env.PrependUnique(LIBPATH = [test_env.get('BUILD_SYSROOT') + '/provisioning'])
#     test_env.AppendUnique(LIBS = ['tinydtls'])
#     test_env.AppendUnique(LIBPATH = [test_env.get('BUILD_SYSROOT') + '/tinydtls'])

if test_env.get('LOGGING'):
	test_env.AppendUnique(CPPDEFINES = ['TB_LOG'])

if target_os in ['msys_nt', 'windows']:
	test_env.AppendUnique(LINKFLAGS = ['/subsystem:CONSOLE'])
	test_env.AppendUnique(LIBS = ['ws2_32', 'iphlpapi', 'kernel32'])
# else:
# 	test_env.PrependUnique(LIBS = ['m'])

######################################################################
# Source files and Targets
######################################################################
stacktests = test_env.Program(target='stacktests', source=['./stacktests.cpp'])
test_env.Decider('timestamp-newer')
cbortests = test_env.Program('cbortests', ['cbortests.cpp'])

#test_env.Install(os.path.join(test_env.get('INSTALL_SYSROOT'), 'test'),  stacktests)

build.utils.install_bin(test_env, stacktests, 'tests')

#test_env.Install(os.path.join(test_env.get('INSTALL_SYSROOT'), 'test'),  cbortests)

build.utils.install_bin(test_env, cbortests, 'tests')

# if env.get('WITH_VALGRIND'):
#         valgrind_xml = 'resource_csdk_stack_test.memcheck'
# else:
#         valgrind_xml = ''

# import test_utils

# if target_os in ['windows']:
#     test_env.AppendENVPath('PATH', [os.path.join(test_env.get('BUILD_DIR'), 'resource', 'csdk')])

# test_utils.run_test(test_env,
#                          valgrind_xml,
#                          'resource/csdk/stack/test/stacktests')
