
= iochibity bazel

Experimenting with bazel build of iotivity 1.3.0

The source is in `src/` and `third_party`.

.bazelrc:
# Bazel option defaults

  # startup --batch --host_jvm_args=-XX:-UseParallelGC
  # import /home/bobs_project/bazelrc

  # build --compilation_mode=dbg  # opt

  # build --crosstool_top=//platforms/rpi3b:toolchain --cpu=armv8

  # build --crosstool_top=//platforms/wrlinux:toolchain --cpu=x86_64

  # build:memcheck --strip=never --test_timeout=3600


WARNING:  The source tree has been reorganized substantially:

* csdk -> //src

* security -> //src/sec

* security/provisioning -> //src/provisioning

* etc.

* src and include subdirs have been removed - source and header files
  go in same director (bazel treats header files as source; this makes
  good sense imho)

* etc.

Building:

[source,sh]
----
$ automake --add-missing  # generates config.guess, config.sub (both required)
$ autoheader && autoconf && ./configure --enable-logging
$ bazel build <target>`
----

where targets are defined by BUILD files.  Examples:

* `$ bazel build src/provisioning`
* `$ bazel build src/comm`
* etc

Run `./configure --help` to see the `--enable-feature` and `--with-lib` options.

Test app:

[source,shell]
----
$ bazel build examples-bazel/OCSample:server
$ bazel build examples-bazel/OCSample:client
----

Output executables will be in `./bazel-bin/examples-bazel/OCSample`

Tested on OS X.  Server runs, but there's still a problem with the client example code.

Had it mostly building on Windows, but that will require some additional work.

Not yet tested on Linux, but should work.


https://ptspts.blogspot.com/2013/12/how-to-make-smaller-c-and-c-binaries.html
