
= OpenOCF

OpenOCF a minimal implementation of the OCF protocol, derived from
https://github.com/iotivity/iotivity[Iotivity].

Differences:

* Minimal, 100% C11 - only the C code from Iotivity, none of the C++ stuff
* Refactoring and renaming.
** API is the same, but source layout and some filenames have been changed.
* The build system is https://bazel.build/[Bazel] instead of Scons.
** Easy cross-compilation (current targets: Raspberry Pi 3B, WindRiver Linux on Intel IoT Gateway, ARM, Android NDK)
* Arduino code is removed.
* Java/Android support has been migrated to a separate repo, https://github.com/OpenOCF/iochibity-java[iochibity-java]
** No Android-specific code in OpenOCF (Work In Progress). Android support in Iotivity involves having the stack call into Android to create objects etc. This has been removed.

WARNING: Developed on OS X. Linux and Windows testing is a little bit behind.

The source is in `src/` and `third_party/`.

WARNING:  The source tree has been reorganized substantially:

* csdk -> //src

* security -> //src/sec

* security/provisioning -> //src/provisioning

* etc.

* src and include subdirs have been removed - source and header files
  go in same director (bazel treats header files as source; this makes
  good sense imho)

* etc.

== Building

OpenOCF uses the https://bazel.build/[Bazel] build system.

Prerequisites: Bazel, GNU autotools. On Windows: msys2, mingw-64.

[source,sh]
----
$ automake --add-missing  # generates config.guess, config.sub (both required)
$ autoheader && autoconf && ./configure --enable-logging
$ bazel build <target>`
----

WARNING: Configuration support for cross-compiling is WIP.

Targets are defined by BUILD files.  Examples:

* `$ bazel build src/provisioning`
* `$ bazel build src/comm`
* etc

Run `./configure --help` to see the `--enable-feature` and `--with-lib` options.

Test app:

[source,shell]
----
$ bazel build examples/simple:server
$ bazel build examples/simple:client
----

Output executables will be in `./bazel-bin/examples/simple

Testing on OS X is up to date. Testing on Linux and Windows is a bit
behind (it does build and run on those platforms but recent work to
support cross-compiling has not yet been tested there).

=== cross-compiling

See
https://github.com/mobileink/bazel-crosscompile[bazel-crosscompile]
for detailed examples of crosscompiling with Bazel.

Summary:

1. Build/install the toolchain.

2. Configure the toolchain for Bazel (CROSSTOOL, etc.).

3. Build the third-party libs needed by your app.

4. Configure the third-party libraries for Bazel (WORKSPACE and BUILD files).

5. Configure your application (BUILD files).

6. Build using the toolchaing

See [cross compiling with bazel] for more info.

Current support for cross-compiling is based on toolchains built by
https://crosstool-ng.github.io/[crosstool-NG].

NOTE: Building crosstool-NG toolchains requires a case-sensitive file
system. On OS X, you will have to create a disk image (dmg file) with
a case-sensitive filesystem. It's a bit of a pain but it works. See
https://www.jaredwolff.com/blog/cross-compiling-on-mac-osx-for-raspberry-pi/[Cross
Compiling on Mac OSX for Raspberry Pi], or search "crosstool-ng os x".

Once your toolchain is set up building is easy. For example, to target
the Raspberry Pi 3b:

[source,sh]
----
$ bazel build examples/simple:server --crosstool_top=//platforms/rpi3b:toolchain
----

See `tools/bazel.rc`. Copy that file to `<root>/.bazelrc` to customize.


== Java/Android

See https://github.com/OpenOCF/iochibity-java[iochibity-java]


=== notes

https://ptspts.blogspot.com/2013/12/how-to-make-smaller-c-and-c-binaries.html

