= iochibity

NOTE: This is a spork ('sperimental fork) derived from the official
https://www.iotivity.org/[Iotivity] 1.1.1 distribution, created for
experimentation.
.

*Goals*

* Minimal - support for Iotivity C kernel only: no C++ and no extras (e.g. nothing from the `services` directory of the official distribution)
* 100% C11
* Darwin support
* Cross-platform build support (e.g. Darwin->Edison, Darwin->Linux, Linux->Edison, etc.)
* Bring some sanity to the build system and source code organization

*Status* as of Dec 2016: Tested on OS X 10.11.6, Ubuntu 14.04, Wind
River Linux (a Dell 3298 IoT Gateway) and the Intel Edison.  The
sample code we have tried runs on all four platforms.  Cross-building
from OS X to Edison has been tested.

WARNING: Based on Iotivity version 1.1.1.  Support for 1.2.1 is
expected but not yet scheduled.

NOTE: Sample programs have been moved to a separate repository:
https://github.com/iotk/iochibity-c[iochibity-c].

NOTE: Java support has been split off into an independent project,
https://github.com/iotk/iotivity-java[iotivity-java].


To build: `$ scons VERBOSE=true 2>&1 | tee build.log`

On OS X, if you run into trouble like missing libs (e.g. libssl), go
with http://brew.sh/[homebrew].


== building

The build mechanism is designed to work with the set of environment
variables as defined in https://github.com/iotk/xc[xc].  Follow the
instructions in https://github.com/iotk/xc[xc README] and then run
scons to build.

WARNING: Building with SECURED=0 is disallowed - only secured builds
are supported.

Cross-platform compilation is partially supported: you can target the
Intel Edison from an OS X development environment.  The plan is to
support Linux as the development host.

NOTE: Unfortunately I do not have Tizen or Windows development
environments so Iochibity has not been tried on either of those.  It
should not be too difficult to make it work, though.

== security

Only secure builds are supported.  This means you must configure
("provision") security to do anything useful.  You have two options:

==== Static provisioning

You will need to write JSON files specifying credential and ACL
information for both client and server.  For an example, see the files
`ocftestclient.json` and `ocftestserver.json` in
https://github.com/iotk/iochibity-java/tree/master/jni-c/example/src/main/resources.

The critical point is that you need to specify a PreShared Key (PSK)
for both client and server.  In the sample files this is done using
the following parts of the "creds" stanza:

[source,json]
----
                "credtype": 1,
                "privatedata": {
                    "data": "AAAAAAAAAAAAAAAA",
                    "encoding": "oic.sec.encoding.raw"
                }
----

The information in the "creds" stanza will be used to set the
credential resource, `oic/sec/cred`, as documented starting on page 86
of the OIC Security Specification (version 1.1).  Here the JSON
"credtype" entry corresponds to the "credtype" resource property; the
value `1` means "Symmetric pair-wise key".  The "privatedata" entry
also corresponds directly to a resource property called "privatedata";
its value, however, has type "oic.sec.privdatatype", which in turn has
properties "encoding" and "data" (see page 90 of the
Spec). `"encoding": "oic.sec.encoding.raw"` means the data field value
is raw hex-encoded data; the `data` field thus specifies the PSK as a
raw hex value.

Both the client and server config files must specify credentials for
both client and server _subject id_ s.

IMPORTANT: The PSK must actually be _shared_ by client and server;
that is, the PSK specified for the _client_ subjectuuid in the client's
config file must be specified as the PSK for the _server_ subjectuuid
in the server's config file, and similarly the other way around.

Use `json2cbor` to generate CBOR files from the JSON files.  Use the
`tools` target to generate the tool: `$ scons tools` will install
`json2cbor` (and `cbordump`) to `${INSTALL_SYSROOT}/bin`.

== tests

All googletest tests have been moved out of the source tree to the
`test` subdirectory.  To build the tests just use the `tests` target:

[source,sh]
----
$ scons tests
----

The resulting executables will be places in `${INSTALL_SYSROOT}/bin`.

Profiling has been removed from the tests.  This is because Valgrind
was causing problems on OS X, but more fundamentally because testing
and performance profiling are completely separate concerns.  Profiling
will be added back as a build option sometime in the future.


* tested on OS X 10.11.6, Ubuntu 14.04, and the Intel Edison (Yocto Linux)
* passes most of the tests, but on OS X valgrind
  crashes on many stacktests and a few others.  This seems to be due
  to problems Valgrind has on El Capitan.  At least some of the
  crashes occur when pthread_join is called in OCStop.  So it looks
  like the tests are passed but crashes occur on thread shutdown
  or sth.
* I've built the stack and run a few of the test apps on OS X 10.11.5,
  Ubuntu 14.04, Wind River Linux on a Dell 3298 gateway, and the Intel
  Edison (latest version, June 2016).

NOTE: I've modified the test sconscripts to default to no valgrind;
see `test/SConscript`.  Everything up to the provisioning unittests
passes with flying colors on the mac.

=== differences from official iotivity codebase

The code is essentially the same, except for the stuff needed to make
it go on Darwin.  However, I've done quite a bit of rearranging,
including some renaming.  I've also migrated a bunch of stuff to
external projects, since I don't think it belongs in the Iochibity
kernel, and this simplifies and speeds things up in various ways.

* C++ code
* android
* cloud
* java
* sample/example code

I also eliminated the dependency on gtest (google test).  Iochibity
treats this just like any other system dependency.  The user is
responsible for obtaining https://github.com/google/googletest[Google
Test] and installing it in the standard location (/usr/local/lib).
Iochibity will feature test for it.  If this causes you trouble please
let me know, it's only been tested on my Mac and Linux systems.

To build and install gtest, follow the instructions at
https://github.com/iotk/xc/tree/master/gtest[googletest for
cross-compiling].

Some other extlibs have been migrated to `resource`: tinycbor, cjson,
timer.  These are essential to the Iotivity kernel but not really
treated as libs, so I see no point in treating them as external libs.
There are only half a dozen or so files involved so I don't foresee
any trouble keeping them up to date.

== java status

The original build system carries out various Java- and Android-related
tasks (like downloading gradle, the Android SDK, etc.) even if the
user has no intention of using either.  Furthermore the build system
for these is far more complicated than it needs to be.  For example,
the build code for compiling the Java bits involves a more or less
opaque construction of a more or less complex gradle instruction, etc.
In fact the Java code can be compiled and jarred up with two simple
commands.  You hardly even need a makefile.  Gradle may be necessary
for Android, but not for Java.

Therefore Java support has been removed from the main repo and
migrated to a separate, independent API/SDK project at
https://github.com/iotk/iotivity-java[iotivity-java].


== build system status

NOTE: You may notice some ld warnings in the build output, complaining
about directories not being found for some -L options.  This is
broken-by-design SCons behavior; you can ignore it.

* android and java code has been removed and migrated to separate independent SDK projects
* lots of clean up of SConscripts.  for example flags like `-Wall` can be set once and for all, no need to set it all over the place.
* gtest has been removed; it is now treated like any other system
  dependency for which we do a feature test.  It's up to the user to
  install it, just like e.g. libuuid and all the other deps.
* only the kernel (resource/) is built by default. at the moment I do
  not need the services so it's a waste of time to build them.
* feature tests are done once, before the build proper begins, in
  `site_scons/build/utils.py`.
* output has been relativized to host.  this makes it possible to use
  virtual machines to develop for multiple hosts using a single
  codebase on a single machine.  For example, on OS X with parallels,
  I can run simultaneous Darwin and Linux builds in the same repo.

Fixing the build system is a work in progress.

The ultimate goal with respect to the SConscript files is that each
should do the minimal amount of work necessary.  Setup of the build
environment itself (feature testing etc.) will be done (by code in
`site_scons`) before the SConscripts are processed.  This is the same
as the logic behind doing `./configure` and then `make` in tradition
autoconf-style build systems.


= etc.

The following doc is outdated but may still be useful.

=== plans

* more testing of darwin port
* make sure it still compiles on Linux, Tizen, etc.
* clean up: make it strictly darwin, w/o dependencies on os x
* add a separate project to support an OS X Framework
* get it into official codebase

==== java support

* support for TARGET_OS=JVM.  A variant on the `generic-java`
branch that is under development.
* make android a separate thing, something like `TARGET_OS=JVM TARGET_ENV=ANDROID`
** android depends on jvm target
=== building

`$ scons`

To see what's happening: `$ scons VERBOSE=true 2>&1 | tee build.log`

You can give it an OS X version:  `$ scons SYS_VERSION=10.11`.

== branches

The `upstream-master` branch cleanly tracks the official Gerrit master
branch.  At least it does when I get around to pulling in the changes.

=== edits

I've marked the edits I made to port to Darwin with GAR, e.g. //GAR,
#GAR, etc.  So you can find them all (I hope) by running `$ grep -R
GAR ./` from the root of a clean repo.

Edits include not only changes needed to get running on darwin, but
also some changes to eliminate warnings.

One major change: in
service/resource-encapsulation/include/RCSResourceObject.h I had to
reorganize the code to eliminate an "incomplete type" error.  I pulled
an embedded class (WeakGuard) out and made it a peer friend class.
related changes also in RCSResource.cpp


I also took the liberty of doing a little renaming where called for.
E.g. some of the samples were called "linux sample foo ..." but
they're not linux specific so I fixed that.  e.g.

service/resource-container/examples/DiscomfortIndexSensorBundle/src/inputSensors/THSensorApp1/SConscript

=== todo

clock_gettime is unsupported on os x; see `service/easy-setup/mediator/richsdk/src/RemoteEnrolleeResource.cpp`

Remove dependency on xcode and OS X version etc. This should be a
strictly Darwin build.  An OS X specific build - e.g. to support an OS
X Framework - should be a separate project.

* don't use 'xcodebuild -showsdks' to get config info - darwin could be used with other toolchains
* use uname -r rather than SYS_VERSION
* use <sys/param.h> (a BSD feature?)

== tools

Some darwin-specific tools you may find useful along the way:

* otool - object file displaying tool

=== dependencies

For Ubuntu, you would use `apt-get` to install dependencies.  On OS X,
the best bet is probably `brew`, the http://brew.sh/[homebrew]
command.  Try `brew search foo` and `brew info foo` to get a feel for
what's what for package foo.

WARNING: Some of this stuff (e.g. libffi, uuid) comes bundled with OS X.  The
problem is that such bundled libraries do not come with `pkg-config`
files, which the Iotivity build scripts use.  So either you have to
install a third-party package that includes a pkg-config file, or you
have to create and install the appropriate pkg-config file.  And the
problem with that is that you do not want to install such in the
system `/usr/lib/pkgconfig` dir, while if you install to
`/usr/local/lib/pkgconfig` they will not be picked up by the build
scripts.  That's because `scons`, the build tool, does not pull in
environment vars, so it only uses the default search path for
`pkg-config`, which is `/usr/lib/pkgconfig`.

* https://developer.apple.com/xcode/download/[xcode] - gcc/g++ compilers.  Starting from xcode 4.2 OS X uses http://clang.llvm.org/get_started.html[clang].
*  https://developer.apple.com/library/ios/technotes/tn2339/_index.html[xcode
  command line tools] Just do a web search on "install os x command
  line tools" or similar to get lots of guidance.

NOTE: Apparently you can install the command line tools, including the
compilers, without also installing xcode, by doing `$ xcode-select
--install`.

* https://www.freedesktop.org/wiki/Software/pkg-config/[pkg-config]
** Not bundled.  `$ brew install pkg-config`
* http://www.bzip.org/[bzip2] - preinstalled in OS X
* https://github.com/01org/tinycbor[tinycbor] - see below
* https://github.com/google/googletest[Google Test] - see below
* http://site.icu-project.org/download[libicu]
** `brew` says "OS X provides libicucore.dylib (but nothing else).".  The brew package is `icu4c`.
* ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/[libpcre]
** `/usr/lib/libpcre.*` bundled with OS X, but may not be enough
** `$ brew install pcre`
** Must be compiled with Unicode support.  To verify, run `$ pcretest -C`.
* libffi.  bundled
** `$ brew install libffi`
* http://linux.die.net/man/3/libuuid[uuid]  Preinstalled on OS X.
* glib-2.0 - required by Bluetooth LE (only?)
** The build scripts use `pkg-config` to check for gio-unix-2.0, which in turn depends on:
*** gobject-2.0
*** gio-2.0, which in turn requires
**** glib-2.0
**** gobject-2.0
** All of that stuff gets installed with glib-2.0
*** `$ brew install glib`  (NB: not glib2)
* http://www.boost.org/[boost]  `$ brew install boost`
* http://scons.org/[scons]  `$brew install scons`
* http://www.stack.nl/~dimitri/doxygen/[doxygen]  `$ brew install doxygen`

== merging

* the following have been migrated out of the source to other projects so can be deleted:

android
java
cloud
all example/sample code

==== feature tests

Feature testing is done once at startup by site_scons/build/utils.py/feature_tests

TODO: get rid of the new build_common/threads.scons


==== gtest

Iochibity makes google test an ordinary lib dependency; it's the
user's responsibility to obtain and install it (standardly, /usr/local/lib?)

Unfortunately gtest stuff is scattered throughout the SConscript files.

==== build tools

iochibity puts build tools in site_scons, so tools/scons stuff is
migrated there.

iochibity runs all feature tests at starttup, so all feature tests
have been migrated out of the SConscript files in the source tree.

For example see resource/c_common/SConscript in 1.1.1, which adds a
feature test for QueryPerformanceFrequency (a Windows feature).  this
needs to be moved to site_scons/build/utils.py/feature_test, or in
this case, maybe to build_common/windows

==== resource directory

RD stuff is mingled in csdk; see resource/csdk/SConscript

==== extlibs

Iochibity moves some stuff into csdk:  cbor, cjson, time


=== gcov etc

e.g. services/scene-mannager/unittests/SConscript

# if target_os not in ['windows', 'winrt']:
#     scene_test_env.AppendUnique(CXXFLAGS = ['-O2', '-g', '-Wall', '-fmessage-length=0'])

# if target_os in ['darwin', 'linux']:
#     scene_test_env.AppendUnique(CXXFLAGS = ['-pthread'])
#     scene_test_env.AppendUnique(LIBS = ['pthread'])

# if not env.get('RELEASE'):
#     if target_os != 'darwin':
#         scene_test_env.AppendUnique(CXXFLAGS = ['--coverage'])
#         scene_test_env.PrependUnique(LIBS = ['gcov'])
#     else:
#         # no -lgcov for os x
# 	scene_test_env.AppendUnique(CPPFLAGS = ['-fprofile-arcs', '-ftest-coverage'])
# 	scene_test_env.PrependUnique(LIBS = ['clang_rt.profile_osx'])

# 	import subprocess
# 	p = subprocess.Popen(['clang', '-print-search-dirs'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
# 	out, err = p.communicate()
# 	libsline = out.splitlines()[1]
# 	clanglibs = libsline.split("libraries: =")[1]

# 	scene_test_env.PrependUnique(LIBPATH = [clanglibs + '/lib/darwin/'])
