# //******************************************************************
# //
# // Copyright 2015 Samsung Electronics All Rights Reserved.
# //
# //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# //
# // Licensed under the Apache License, Version 2.0 (the "License");
# // you may not use this file except in compliance with the License.
# // You may obtain a copy of the License at
# //
# //      http://www.apache.org/licenses/LICENSE-2.0
# //
# // Unless required by applicable law or agreed to in writing, software
# // distributed under the License is distributed on an "AS IS" BASIS,
# // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# // See the License for the specific language governing permissions and
# // limitations under the License.
# //
# //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
Import('env')
import build.utils

tools_env = env.Clone()
src_dir = '#resource/csdk' # tools_env.get('SRC_DIR')

install_sysroot = env.get('INSTALL_SYSROOT')

######################################################################
# Build flags
######################################################################
tools_env.PrependUnique(CPPPATH = [src_dir + '/cjson',
				   src_dir + '/cbor',
                                   src_dir + '/stack',
                                   src_dir + '/stack/internal',
                                   src_dir + '/logger',
                                   src_dir + '/connectivity/api',
                                   src_dir + '/security',
                                   src_dir + '/security/ocsecurity',
                                   src_dir + '/connectivity/lib/libcoap-4.1.1'])

tools_env.AppendUnique(LIBPATH = [install_sysroot])
tools_env.AppendUnique(RPATH = [env.get('BUILD_DIR')])
tools_env.PrependUnique(LIBS = ['chibity'])

######################################################################
# Source files and Targets
######################################################################
json2cbor = tools_env.Program('json2cbor', ['json2cbor.c'])
Alias("json2cbor", [json2cbor])

#build.utils.append_target(env, 'json2cbor')
build.utils.install_bin(env, json2cbor, 'json2cbor')
