#******************************************************************
#
# Copyright 2014 Intel Mobile Communications GmbH All Rights Reserved.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Import('env')
import os
import os.path
unittests_env = env.Clone()

target_os = env.get('TARGET_OS')

# # SConscript file for Local PKI google tests
# gtest_env = SConscript('#extlibs/gtest/SConscript')
unittests_env = env.Clone()
src_dir = unittests_env.get('SRC_DIR')
pi_dir = os.path.join(src_dir, 'plugins')
build_dir = env.get('BUILD_DIR')

######################################################################
# Build flags
######################################################################
unittests_env.PrependUnique(CPPPATH = [
                os.path.join(pi_dir, 'include'),
                os.path.join(src_dir, 'resource', 'csdk', 'stack', 'include')
		])

unittests_env.AppendUnique(LIBPATH = [unittests_env.get('BUILD_DIR')])
unittests_env.PrependUnique(LIBS = [
		'plugin_interface',
		'oc',
		'octbstack',
		'oc_logger',
		'connectivity_abstraction',
		'coap',
		'gtest',
		'gtest_main'
		])

if unittests_env.get('LOGGING'):
	unittests_env.AppendUnique(CPPDEFINES = ['TB_LOG'])

######################################################################
# Source files and Targets
######################################################################
piunittests = unittests_env.Program('piunittests', ['plugininterfacetest.cpp'])

Alias("piunittests", [piunittests])

env.AppendTarget('piunittests')

if env.get('WITH_VALGRIND'):
        valgrind_xml = 'plugins_unittests.memcheck'
else:
        valgrind_xml = ''

import runtest.RunTest

runtest.RunTest.run_test(unittests_env,
                         valgrind_xml,
                         'plugins/unittests/piunittests')

