#******************************************************************
#
# Copyright 2014 Intel Mobile Communications GmbH All Rights Reserved.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Import('env')
import os
import os.path
randomtest_env = env.Clone()

target_os = env.get('TARGET_OS')

src_dir = randomtest_env.get('SRC_DIR')

######################################################################
# Build flags
######################################################################
home = os.environ['HOME']
gtest_dir = home + '/.iotivity.d/gtest-1.7.0'

randomtest_env.PrependUnique(CPPPATH = [gtest_dir + '/include'
				       ,'../include'
				       ,'./../../logger/include'
				       ,'./../../../oc_logger/include'])

randomtest_env.AppendUnique(LIBPATH = [env.get('BUILD_DIR')
				      ,'/usr/local/lib'
				      ,gtest_dir + '/lib/.libs'])

if target_os == 'darwin':
    # randomtest_env.AppendUnique(CFLAGS = [
    # '-Wl,-dylib_file,/usr/local/lib/libgtest.dylib:./extlibs/gtest/gtest-1.7.0/lib/.libs/libgtest.dylib',
    # '-dylib_file /usr/local/lib/libgtest_main.dylib:./extlibs/gtest/gtest-1.7.0/lib/.libs/libgtest_main.dylib'
    # ])
    randomtest_env.PrependUnique(LIBS = ['m'
    				      ,'gtest'
				      ,'gtest_main'
    				      ,'octbstack'])
else:
    randomtest_env.PrependUnique(LIBS = ['m'
					,'gtest'
					,'gtest_main'
    				      	,'octbstack'
					,'uuid'])

if env.get('LOGGING'):
	randomtest_env.AppendUnique(CPPDEFINES = ['TB_LOG'])

######################################################################
# Source files and Targets
######################################################################
randomtests = randomtest_env.Program('randomtests', ['linux/randomtest.cpp'])

Alias("test", [randomtests])

env.AppendTarget('test')
if env.get('TEST') == '1':
	target_os = env.get('TARGET_OS')
	if target_os in ['darwin', 'linux']:
                from tools.scons.RunTest import *
                run_test(randomtest_env,
                         'resource_csdk_random_test.memcheck',
                         'resource/c_common/ocrandom/test/randomtests')
