##
# CA build script
##

Import('env')

target_os = env.get('TARGET_OS')
transport = env.get('TARGET_TRANSPORT')
build_sample = env.get('BUILD_SAMPLE')
with_ra = env.get('WITH_RA')
with_tcp = env.get('WITH_TCP')
with_mq = env.get('WITH_MQ')

print "Connectivity Configuration (resource/csdk/connectivity/SConscript):"
print "\tTarget Transport is %s" % transport
print "\tTarget OS is %s" % target_os
print "\tBuild with Sample? %s" % build_sample
print "MQ flag is %s" % with_mq

targets_disallow_multitransport = ['arduino']

if target_os in targets_disallow_multitransport:
    if ('ALL' in transport) or (len(transport) != 1):
        print "*** Error invalid option values: TARGET_TRANSPORT"
        print "%s disallowed until testing can validate use of multiple transports on %s %d" % (transport, target_os, len(transport))
        Exit(1)

env.SConscript('./src/SConscript')
