#******************************************************************
#
# Copyright 2014 Intel Mobile Communications GmbH All Rights Reserved.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


Import('env')
import os
import build.utils

local_env = env.Clone()

target_os = local_env.get('TARGET_OS')

build_sysroot = local_env.get('BUILD_SYSROOT')

# Add platform-specific helper library
if target_os in ['windows', 'msys_nt']:
	SConscript('windows/SConscript')

# local_env.AppendUnique(CPPPATH = ['#resource/c_common'])
#             os.path.join(Dir('.').abspath),
#             os.path.join(Dir('.').abspath, 'oic_malloc', 'include'),
#             os.path.join(Dir('.').abspath, 'oic_string', 'include'),
#             os.path.join(Dir('.').abspath, 'oic_time', 'include'),
#             os.path.join(Dir('.').abspath, 'ocrandom', 'include')
#         ])

if target_os == 'tizen':
	local_env.AppendUnique(LIBPATH = [build_sysroot])
else:
	local_env.AppendUnique(LIBPATH = [os.path.join(build_sysroot, 'c_common')])

if local_env.get('TB_LOG'):
	local_env.AppendUnique(LIBS = 'logger')
	local_env.AppendUnique(CPPPATH = ['#resource/csdk/logger'])

local_env.AppendUnique(LIBPATH = [build_sysroot + '/lib'])

######################################################################
# Source files and Targets
######################################################################
common_src = [
	'oic_string.c',
	'oic_malloc.c',
	'oic_time.c',
	'ocrandom.c',
	'oc_uuid.c'
	]

if target_os in ['darwin', 'poky-edison', 'linux']:
   common_src = common_src + ['unix/ocrandom_seed.c']

commonlib = local_env.StaticLibrary('c_common', common_src)
# local_env.InstallTarget(commonlib, 'c_common')
# local_env.Install(build_sysroot, commonlib)
# local_env.UserInstallTargetLib(commonlib, 'c_common')

build.utils.install_headers(local_env, ['platform_features.h'], '', 'chibity')
# build.utils.install_lib(local_env, commonlib, 'c_common')

# env.PrependUnique(LIBS = ['c_common'])
