= transport layer

== monitoring

The routines that do the work:

OCDefaultAdapterStateChangedHandler - NOP (ocstack.c)
OCDefaultConnectionStateChangedHandler - NOP for UDP, fixup observers for TCP chg (ocstack.c)

TCP and Cloud only:
OCAdapterStateChangedHandler - TCP nif changes (occonnectionmanager.c)
OCConnectionStateChangedHandler - TCP connection changes (occonnectionmanager.c)

These callbacks get packaged in pairs in a CANetworkCallback_t struct,
 which then gets added to g_networkChangeCallbackList (via a
 convoluted initialization routine).

We also have:

CAAdapterChangedCallback (cainterfacecontroller.c) iteratees over
g_networkChangeCallbackList. For each it creates a
CANetworkCallbackThreadInfo_t and adds it to the
g_networkChangeCallbackThread dispatch queue.

CAAdapterChangedCallback gets put in g_networkChangeCallback, which
gets called by CA<transport>AdapterHandler, which is added to
g_adapterCallbackList (via CAStart<transport> ->
CAIPStartNetworkMonitor -> CAIPSetNetworkMonitorCallback).

This happens once per transport, so g_adapterCallbackList will have an
entry for each transport.

When a NWIF change is detected CAFindInterfaceChange is called, with
call CAIPPassNetworkChangesToAdapter, which iterates over
g_adapterCallbackList, so the CB for each transport is called.  That
CB then iterates over the CBs in g_networkChangeCallbackList and adds
them to the g_networkChangeCallbackThread dispatch queue.  The queue
is serviced by ??, which finally invokes the handlers mentioned at the
top above.

==== old notes


Parallel structure: cainteracecontroller and cautilinterface setup
callbacks etc. So does the transport-specific code. E.g. in
cainterfacecontroller we have g_networkChangeCallbackList, and in
caipnwmonitor0 we have g_adapterCallbackList.

So the question is: who needs to be notified about network status
changes, and why.

For specific transport, implementation is split across a generic component (caipnwmonitor0)
and a platform-specific component (e.g. caipnwmonitor_posix)

"Network" level logic (in cautilinterface, cainterfacecontroller): 

For setup, OCCMInitialize (occonnectionmanager) calls
CARegisterNetworkMonitorHandler calls CASetNetworkMonitorCallbacks
calls AddNetworkStateChangedCallback.  The callback passed from the
top is static OCAdapterStateChangedHandler. Which doesn't seem to do
much.

Status change event handling logic:

Using select on a netlink socket, the network listening looper detects
a netlink event like RTM_NEWADDR is ready to be read. It calls
CAFindInterfaceChange, which gets the msg (recvmsg on netlink
socket). It then calls CAIPPassNetworkChangesToAdapter, passing either
CA_INTERFACE_UP or DOWN. That routine calls the
<transport>_status_change_handler, which in turn calls:
a) CAUpdateStoredIPAddressInfo
b) CAAdapterChangedCallback - this propagates the change to cainterfacecontroller
c) CAcloseSslConnectionAll if status is DOWN.

CAUpdateStoredIPAddressInfo converts the Iface info to Endpoint
structs, which it adds to the global list of local (own) EPs
(g_local_endpoints)

CAAdapterChangedCallback is in cainterfacecontroller: iterates over
g_networkChangeCallbackList. creates a threadinfo struct, adds it to
CAQueueingThreadAddData, then calls callbacks

NOTE:  we also have monitoring in cainterfacecontroller.c:

* CAAdapterChangedCallback (called by status chg handler)
* CAConnectionChangedCallback

data types:

struct: CAInterface_t (which is actually an IF address struct)
API:
* CANewInterfaceItem
* CAIPGetInterfaceInformation

struct CAIPCBData_t - linked list of (ip_status_change_event_handler, transport_type)

Status change event handler signature:
    void (*)(CATransportAdapter_t transport_type, CANetworkStatus_t status);


Globals:

* g_networkChangeCallbackList (cainterfacecontroller)

* g_network_interfaces  (@was g_netInterfaceList). API:
** CAIPInitializeNetworkAddressList @was CAIPInitializeNetworkMonitorList (delegated to platform-specific impl)
** CAAddToNetworkoAddressList @was CAAddNetworkMonitorList
** CAIPDestroyNetworkAddressList @was CAIPDestroyNetworkMonitorList
** CACmpNetworkList @was CACmpNetworkList

Note that NetworkMonitorList really means list of interface structs

* g_adapterCallbackList

CAIPSetNetworkMonitorCallback
CAIPUnSetNetworkMonitorCallback
CAIPStartNetworkMonitor
CAIPStopNetworkMonitor

CAIPStartNetworkMonitor
CAIPStopNetworkMonitor

CAIPPassNetworkChangesToAdapter
CAGetPollingInterval

CAIPPassNetworkChangesToAdapter


== udpip

caipnwmonitor.h - one

caipnwmonitor.c - one per platform. however, some of the routines are
the same across all (most) platforms:

    CAIPSetNetworkMonitorCallback - same

    CAIPUnSetNetworkMonitorCallback - same

    CAIPGetInterfaceInformation - different on the surface but mostly the same

    CAFindInterfaceChange - linux, android are different

    CAIPStartNetworkMonitor

        linux: calls CAIPInitializeNetworkMonitorList, then CAIPSetNetworkMonitorCallback
	android: calls CAIPJniInit (which creates Java obj that registers callbacks), then CAIPSetNetworkMonitorCallback

    CAIPStopNetworkMonitor - slightly different, android version calls into jni

    CAProcessNewInterface

CAGetLinkLocalZoneIdInternal

internal routines:

    CAGetPollingInterval - same

    CAIPPassNetworkChangesToAdapter - same


    CANewInterfaceItem - same

    CAGetLinkLocalZoneIdInternal - same

Linux only:

    CAIPInitializeNetworkMonitorList
    CAIPDestroyNetworkMonitorList
    CACmpNetworkList
    CAAddNetworkMonitorList
    CARemoveNetworkMonitorList


Android only:

CAParsingNetorkInfo

CAAddInterfaceItem
