#******************************************************************
#
# Copyright 2015 Intel Mobile Communications GmbH All Rights Reserved.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

import os

Import('env')

src_dir = env.get('SRC_DIR')

target_os = env.get('TARGET_OS')
target_arch = env.get('TARGET_ARCH')

home = env.get('HOME')
cbor_dir = home + '/.iotivity.d/' + target_os + '/' + target_arch + '/tinycbor'

if not os.path.exists(cbor_dir):
    print '''
*********************************** Error: ****************************************
* Please download cbor using the following command:                               *
*     $ git clone https://github.com/01org/tinycbor.git {}/.iotivity.d/{}/{}/tinycbor *
***********************************************************************************
'''.format(home, target_os, target_arch)
    Exit(1)

cbor_src = [
    os.path.join(cbor_dir,'src/cborparser.c'),
    os.path.join(cbor_dir,'src/cborencoder.c'),
    os.path.join(cbor_dir,'src/cborerrorstrings.c'),
    ]

env['cbor_files'] = cbor_src
env.AppendUnique(CPPPATH  = [os.path.join(cbor_dir, 'src')])


