java_library(
    name = "common",
    srcs = glob(["org/openocf/test/*.java"]),
    #deps = ["@openocf_java//:openocf_japi"],
    deps = ["//bindings/javalang:openocf_japi"],
    visibility = ["//visibility:public"]
    # visibility = ["//bindings/java/demos/Server:__pkg__",
    #               "//bindings/java/demos/Client:__pkg__"]
)
