#######################################################
#	Build Common Util
#######################################################

Import('env')
import os.path

ca_os = env.get('TARGET_OS')
ca_transport = env.get('TARGET_TRANSPORT')
target_os = env.get('TARGET_OS')
project_root = env.get('SRC_DIR')
root_dir = os.path.join(project_root, 'resource', 'csdk', 'connectivity')
src_dir = os.path.join(root_dir, 'util', 'src')

######################################################################
# Source files to build common for platforms
######################################################################

env.AppendUnique(CA_SRC = [os.path.join('./../util/src/cautilinterface.c')])

if target_os == 'android':
    if (('BLE' in ca_transport) or ('ALL' in ca_transport)):
        env.AppendUnique(CA_SRC = [
			os.path.join(src_dir, 'camanager', ca_os, 'caleconnectionmanager.c'),
			os.path.join(src_dir, 'camanager', ca_os, 'caleautoconnector.c'),
			os.path.join(src_dir, 'camanager', ca_os, 'camanagerleutil.c'),
			os.path.join(src_dir, 'camanager', ca_os, 'camanagerdevice.c')])

        if (('BT' in ca_transport) or ('ALL' in ca_transport)):
			env.AppendUnique(CA_SRC = [
			os.path.join(src_dir, 'btpairing' ,ca_os, 'cabtpairing.c')])