= cross-compiling

You will have to run ./configure to get the appropriate #define
macros. that's a little tricky; see
https://github.com/mobileink/bazel-crosscompile[bazel-crosscompile]
for detailed examples of crosscompiling with Bazel. The relevant files
here are in link:platforms[platforms/] and link:WORKSPACE[WORKSPACE].

Summary:

1. Build/install the toolchain.

2. Configure the toolchain for Bazel (CROSSTOOL, etc.).

3. Build the third-party libs needed by your app.
** run ./configure with appropriate parameters
** run bazel build

4. Configure the third-party libraries for Bazel (WORKSPACE and BUILD files).

** this may include running ./configure or similar, to get the #define
   macros needed for the target host. note you must run autoconf with
   the target toolchain. see the example doc for details

5. Configure your application (BUILD files).

**  may include running ./configure, as above

6. Build using the toolchain

Current support for cross-compiling is based on toolchains built by
https://crosstool-ng.github.io/[crosstool-NG].

NOTE: Building crosstool-NG toolchains requires a case-sensitive file
system. On OS X, you will have to create a disk image (dmg file) with
a case-sensitive filesystem. It's a bit of a pain but it works. See
https://www.jaredwolff.com/blog/cross-compiling-on-mac-osx-for-raspberry-pi/[Cross
Compiling on Mac OSX for Raspberry Pi], or search "crosstool-ng os x".

(Cmd line mount: `$ sudo hdiutil attach /path/to/diskimage.dmg`)

Once your toolchain is set up building is easy. For example, to target
the Raspberry Pi 3b:

[source,sh]
----
$ bazel build examples/simple:server --crosstool_top=//platforms/rpi3b:toolchain
----

See link:tools/bazel.rc[tools/bazel.rc]. Copy that file to `<root>/.bazelrc` to customize.


== Java/Android

See https://github.com/OpenOCF/iochibity-java[iochibity-java]


== using party libs

Building third-party libs:

$ export PATH="${PATH}:/path/to/toolchain/bin"

e.g. /Volumes/CrossToolNG/armv8-rpi3-linux-gnueabihf/bin"

$ export COSYSROOT=$HOME/cosysroots/rpi3b

Adjusted to match rpi3b builtin ncurses settings:

ncurses:

-P Inhibit generation of linemarkers in the output from the preprocessor

--build triple: run $ bash --version
x86_64-pc-linux-gnu
              # --host=armv8-rpi3-linux-gnueabihf \ apple crosstools-ng
$ ./configure --build=x86_64-apple-darwin \
	      --host=arm-rpi-4.9.3-linux-gnueabihf \
              --enable-kernel=4.9.35 \
              --prefix=/usr \
	      --with-terminfo-dirs="/etc/terminfo:/lib/terminfo:/usr/share/terminfo" \
	      --with-default-terminfo-dir="/etc/terminfo" \
	      --mandir="/usr/share/man" \
	      --without-manpages \
	      --with-shared \
	      --libdir="/usr/lib/arm-linux-gnueabihf" \
              CPPFLAGS="-P"

              // CPPFLAGS="-P -I$COSYSROOT/usr/include" \
              // LDFLAGS="-L$COSYSROOT/lib \
	      // -L$COSYSROOT/usr/lib"

$ make
$ make DESTDIR=$COSYSROOT install


cdk: we installed ncurses in cosysroots/rpi3b, so we need to fix CPPFLAGS and LDFLAGS:

$ ./configure --build=x86_64-apple-darwin \
              --host=armv8-rpi3-linux-gnueabihf \
              --enable-kernel=4.9.35 \
              --prefix=/usr \
	      --with-terminfo-dirs="/etc/terminfo:/lib/terminfo:/usr/share/terminfo" \
	      --with-default-terminfo-dir="/etc/terminfo" \
	      --mandir="/usr/share/man" \
	      --without-manpages \
	      --libdir="/usr/lib/arm-linux-gnueabihf" \
              CPPFLAGS="-P -I$COSYSROOT/usr/include" \
	      LDFLAGS="-L$COSYSROOT/usr/lib/arm-linux-gnueabihf"


              // LDFLAGS="-L$COSYSROOT/lib \
	      // -L$COSYSROOT/usr/lib"

	      // --with-shared \
$ make
$ make DESTDIR=$COSYSROOT install

