= newbuild

The official build system is a mess.  let's start over.

Resources:

* https://github.com/mbr/scons-tools[scons-tools] - a collection of tools, to go in `site_scons/site_tools`


=== security

Building with SECURED=1 enables dtls

    * __WITH_DTLS__ is defined

X509 - this is a mess.  The following macros are tested in various places:

    * DTLS_WITH_X509
    * __WITH_X509__

The idea seems to be that DTLS_WITH_X509 is a scons param, which is used to set __WITH_X509__

TODO: replace all this with WITH_X509 param which is propagated.

    * X509_DEBUG
    * WITH_SHA256

=== misc

* eliminate platform defs, e.g. -D__darwin__, -D_DARWIN_C_SOURCE

== cross-compiling

==== osx to edison

The following post contains essential info.  In particular, how to
deal with the missing flex lib ("dyld: Library not loaded: @loader_path/../../lib/libfl.2.dylib")

* https://gist.github.com/pbosetti/027125c4ba066f51bf2c[Cross compiling setup from OS X to Intel Edison poky linux]

Summary:

* obtain flex tarball:  `wget http://downloads.sourceforge.net/project/flex/flex-2.6.0.tar.bz2?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fflex%2Ffiles%2F&ts=1471541559&use_mirror=heanet`

* rename it if need be to flex-2.6.0.tar.bz2 and detar it

```
$ bunzip flex-2.6.0.tar.bz2 && tar xvf flex-2.6.0.tar
$ cd flex-2.6.0
$ ./configure --prefix=/opt/poky-edison/1.7.3/sysroots/i386-pokysdk-darwin/usr/ '--target=i586-poky-linux'
CFLAGS='-arch i386'
$ make -j8
$ sudo make install
```

NOTE:  The cited blog post omits the --target arg to configure.  You need that.

To verify the build use `file`; libfl.2.dylib should have the same type as the other tools

[source,sh]
----
$ file /opt/poky-edison/1.7.3/sysroots/i386-pokysdk-darwin/usr/bin/i586-poky-linux/i586-poky-linux-gcc
/opt/poky-edison/1.7.3/sysroots/i386-pokysdk-darwin/usr/lib/libfl.2.dylib: Mach-O dynamically linked shared library i386

$ file /opt/poky-edison/1.7.3/sysroots/i386-pokysdk-darwin/usr/lib/libfl.2.dylib
/opt/poky-edison/1.7.3/sysroots/i386-pokysdk-darwin/usr/lib/libfl.2.dylib: Mach-O dynamically linked shared library i386
----


== testing

We need to test all permutations:

* SECURED= 0 | 1
* RELEASE= true | false
* ROUTING= EP | GW
* WITH_TCP= true | false

App-level (C++ sdk):

* WITH_RA= true | false
* WITH_RD= true | false
