/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class  */

#ifndef _Included_
#define _Included_
#ifdef __cplusplus
extern "C" {
#endif
#undef _MAX_ARRAY_SIZE
#define _MAX_ARRAY_SIZE 2147483639L
#undef _serialVersionUID
#define _serialVersionUID 8683452581122892189LL
#undef _DEFAULT_CAPACITY
#define _DEFAULT_CAPACITY 10L
#undef _MAX_ARRAY_SIZE
#define _MAX_ARRAY_SIZE 2147483639L
#ifdef __cplusplus
}
#endif
#endif
