/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openocf_engine_OCFClientSP */

#ifndef _Included_openocf_engine_OCFClientSP
#define _Included_openocf_engine_OCFClientSP
#ifdef __cplusplus
extern "C" {
#endif
#undef openocf_engine_OCFClientSP_CLIENT
#define openocf_engine_OCFClientSP_CLIENT 0L
#undef openocf_engine_OCFClientSP_SERVER
#define openocf_engine_OCFClientSP_SERVER 1L
#undef openocf_engine_OCFClientSP_CLIENT_SERVER
#define openocf_engine_OCFClientSP_CLIENT_SERVER 2L
#undef openocf_engine_OCFClientSP_GATEWAY
#define openocf_engine_OCFClientSP_GATEWAY 3L
#undef openocf_engine_OCFClientSP_QOS_LOW
#define openocf_engine_OCFClientSP_QOS_LOW 0L
#undef openocf_engine_OCFClientSP_QOS_MEDIUM
#define openocf_engine_OCFClientSP_QOS_MEDIUM 1L
#undef openocf_engine_OCFClientSP_QOS_HIGH
#define openocf_engine_OCFClientSP_QOS_HIGH 2L
#undef openocf_engine_OCFClientSP_QOS_NA
#define openocf_engine_OCFClientSP_QOS_NA 3L
/*
 * Class:     openocf_engine_OCFClientSP
 * Method:    coExhibit
 * Signature: (Lopenocf/app/CoResourceSP;)V
 */
JNIEXPORT void JNICALL Java_openocf_engine_OCFClientSP_coExhibit
  (JNIEnv *, jclass, jobject);

/*
 * Class:     openocf_engine_OCFClientSP
 * Method:    configurePlatformSP
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_openocf_engine_OCFClientSP_configurePlatformSP
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     openocf_engine_OCFClientSP
 * Method:    configureDeviceSP
 * Signature: (Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_openocf_engine_OCFClientSP_configureDeviceSP
  (JNIEnv *, jclass, jstring, jobjectArray, jstring, jobjectArray);

/*
 * Class:     openocf_engine_OCFClientSP
 * Method:    registerDefaultCoResourceSP
 * Signature: (Lopenocf/app/CoResourceSP;)Lopenocf/app/CoResourceSP;
 */
JNIEXPORT jobject JNICALL Java_openocf_engine_OCFClientSP_registerDefaultCoResourceSP
  (JNIEnv *, jclass, jobject);

/*
 * Class:     openocf_engine_OCFClientSP
 * Method:    registerCoResourceSP
 * Signature: (Lopenocf/app/CoResourceSP;)Lopenocf/app/CoResourceSP;
 */
JNIEXPORT jobject JNICALL Java_openocf_engine_OCFClientSP_registerCoResourceSP
  (JNIEnv *, jclass, jobject);

/*
 * Class:     openocf_engine_OCFClientSP
 * Method:    registeredCoResourceSPs
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_openocf_engine_OCFClientSP_registeredCoResourceSPs
  (JNIEnv *, jclass);

/*
 * Class:     openocf_engine_OCFClientSP
 * Method:    getRelatedCoResourceSPs
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_openocf_engine_OCFClientSP_getRelatedCoResourceSPs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
