/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openocf_engine_OCFCommonSP */

#ifndef _Included_openocf_engine_OCFCommonSP
#define _Included_openocf_engine_OCFCommonSP
#ifdef __cplusplus
extern "C" {
#endif
#undef openocf_engine_OCFCommonSP_CLIENT
#define openocf_engine_OCFCommonSP_CLIENT 0L
#undef openocf_engine_OCFCommonSP_SERVER
#define openocf_engine_OCFCommonSP_SERVER 1L
#undef openocf_engine_OCFCommonSP_CLIENT_SERVER
#define openocf_engine_OCFCommonSP_CLIENT_SERVER 2L
#undef openocf_engine_OCFCommonSP_GATEWAY
#define openocf_engine_OCFCommonSP_GATEWAY 3L
#undef openocf_engine_OCFCommonSP_QOS_LOW
#define openocf_engine_OCFCommonSP_QOS_LOW 0L
#undef openocf_engine_OCFCommonSP_QOS_MEDIUM
#define openocf_engine_OCFCommonSP_QOS_MEDIUM 1L
#undef openocf_engine_OCFCommonSP_QOS_HIGH
#define openocf_engine_OCFCommonSP_QOS_HIGH 2L
#undef openocf_engine_OCFCommonSP_QOS_NA
#define openocf_engine_OCFCommonSP_QOS_NA 3L
/*
 * Class:     openocf_engine_OCFCommonSP
 * Method:    configuration
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_openocf_engine_OCFCommonSP_configuration
  (JNIEnv *, jclass);

/*
 * Class:     openocf_engine_OCFCommonSP
 * Method:    Init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_openocf_engine_OCFCommonSP_Init__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     openocf_engine_OCFCommonSP
 * Method:    Init
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_openocf_engine_OCFCommonSP_Init__III
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     openocf_engine_OCFCommonSP
 * Method:    XOCRegisterPersistentStorageHandler
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_openocf_engine_OCFCommonSP_XOCRegisterPersistentStorageHandler
  (JNIEnv *, jobject, jobject);

/*
 * Class:     openocf_engine_OCFCommonSP
 * Method:    OCStartMulticastServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_openocf_engine_OCFCommonSP_OCStartMulticastServer
  (JNIEnv *, jobject);

/*
 * Class:     openocf_engine_OCFCommonSP
 * Method:    OCStopMulticastServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_openocf_engine_OCFCommonSP_OCStopMulticastServer
  (JNIEnv *, jobject);

/*
 * Class:     openocf_engine_OCFCommonSP
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_openocf_engine_OCFCommonSP_run
  (JNIEnv *, jclass);

/*
 * Class:     openocf_engine_OCFCommonSP
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_openocf_engine_OCFCommonSP_stop
  (JNIEnv *, jclass);

/*
 * Class:     openocf_engine_OCFCommonSP
 * Method:    OCCancel
 * Signature: (Ljava/lang/Object;ILjava/lang/Object;B)V
 */
JNIEXPORT void JNICALL Java_openocf_engine_OCFCommonSP_OCCancel
  (JNIEnv *, jobject, jobject, jint, jobject, jbyte);

#ifdef __cplusplus
}
#endif
#endif
