/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openocf_engine_ActionSet */

#ifndef _Included_openocf_engine_ActionSet
#define _Included_openocf_engine_ActionSet
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
