#******************************************************************
#
# Copyright 2014 Intel Mobile Communications GmbH All Rights Reserved.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

##
# 'resource' sub-project main build script
#
##

Import('env')

target_os = env.get('TARGET_OS')
src_dir = env.get('SRC_DIR')

# Build liblogger
SConscript('csdk/logger/SConscript')

if target_os not in ['arduino', 'darwin', 'ios', 'android', 'msys_nt', 'windows']:
	env.AppendUnique(LIBS=['rt'])

# Build libcoap
SConscript('csdk/connectivity/lib/libcoap-4.1.1/SConscript')

# Build C Common dependencies
SConscript('c_common/SConscript')

# Build connectivity
SConscript('csdk/connectivity/SConscript')

if env.get('ROUTING') in ['GW', 'EP']:
	# Build Routing
	SConscript('csdk/routing/SConscript')

# Build libocsrm
SConscript('csdk/security/SConscript')

# Build liboctbstack
SConscript('csdk/SConscript')

if target_os not in ['arduino','ios']:
	# Build liboc_logger
	SConscript('oc_logger/SConscript')

	# Build liboc
	SConscript('src/SConscript')

if target_os not in ['arduino','ios','android']:
	# Build examples
	SConscript('examples/SConscript')

# Build Common unit tests
#GAR    	if target_os != 'darwin':
SConscript('c_common/oic_string/test/SConscript')
SConscript('c_common/oic_malloc/test/SConscript')
SConscript('c_common/oic_time/test/SConscript')
SConscript('c_common/ocrandom/test/SConscript')

# Build C unit tests
SConscript('csdk/stack/test/SConscript')

SConscript('csdk/connectivity/test/SConscript')

# Build Security Resource Manager unit tests
SConscript('csdk/security/unittest/SConscript')

# Build C++ unit tests
SConscript('unittests/SConscript')

# Build Provisioning API unit test
if env.get('SECURED') == '1':
        SConscript('csdk/security/provisioning/unittest/SConscript')
	SConscript('provisioning/unittests/SConscript')


if target_os in ['darwin', 'linux', 'windows']:
	# Build C Samples
	SConscript('csdk/stack/samples/linux/SimpleClientServer/SConscript')

	# Build secure samples
	SConscript('csdk/stack/samples/linux/secure/SConscript')

# if target_os == 'osx':
# 	env.Command('../../out/darwin/iotivity-csdk.framework',None,src_dir + '/tools/darwin/mkfwk_osx.sh'

elif target_os == 'arduino':
	SConscript('csdk/stack/samples/arduino/SimpleClientServer/ocserver/SConscript')

elif target_os == 'msys_nt':
	# Build secure samples. Using linux samples for now.
	SConscript('csdk/stack/samples/linux/secure/SConscript')

	# Build C/C++ unit tests
	SConscript('unit_tests.scons')
