package openocf.ocfresources;
// package org.iotivity.base;

import java.util.List;
import java.util.ArrayList;

/**
 * This class is expected as input for device properties. Device name and types are mandatory
 * and expected from the application. Device id of type UUID will be generated by the stack.
 */
public class InfoDevice {

    private String mDeviceName;
    private List<String> mDeviceTypes;
    private String mSpecVersion;      // core.major.minor
    private String mDataModelVersions; // <vertical>.major.minor

    public InfoDevice(String deviceName, List<String> deviceTypes) {
        this.mDeviceName = deviceName;
        this.mDeviceTypes = deviceTypes;
    }

    public InfoDevice(String deviceName,
			String specVersion,
			String dataModelVersions) {
        this.mDeviceName = deviceName;
        this.mSpecVersion = specVersion;
        this.mDataModelVersions = dataModelVersions;
        this.mDeviceName = deviceName;
        this.mDeviceTypes = new ArrayList<String>(){{
		add("oic.wk.d");
	    }};
    }

    public String getDeviceName() {
        return mDeviceName;
    }

    public List<String> getDeviceTypes() {
        return mDeviceTypes;
    }
}
