cc_library(
    name = "config",
    hdrs = ["iotivity_config.h",
            "iotivity_constants.h",
            "iotivity_debug.h",
            "system.h",
            "transport_types.h"],
    visibility = ["//visibility:public"])
