= udpip

WARNING: doc is Work In Progress

Tasks:

* observe (recv) incoming data messages - select/recvmsg on all data sockets
* exhibit (send) messages
* monitor interface/addr status messages - netlink socket (CARegisterForAddressChanges) select/recvmsg


Observation/monitoring flow (caipserver.c):

CAIpStartServer CAReceiveHandler to threadpool
CAReceiveHandler loop => CAFindReadyMessage => CASelectReturned
for data messages, CASelectReturned calls CAReceiveMessage
for if change messages, CASelectReturned calls CAFindInterfaceChange, CAProcessNewInterface
for shutdown messages, CASelectReturned quits

CAFindInterfaceChange -> CAIPGetInterfaceInformation
CAIPGetInterfaceInformation => getifaddrs, converts result to list of CAInterface_t

Naming fixes:
CARegisterForAddressChanges -> initialize_interface_monitor (i.e. create the netlink socket)
CAFindReadyMessage          -> wait_for_ready_interfaces
CASelectReturned            -> process_ready_interfaces
CAReceiveMessage            -> handle_data_message
CAFindInterfaceChange       -> handle_network_change_message
CAIPGetInterfaceInformation -> get_ifaddrs_info
CAProcessNewInterface       -> join_multicast_group


* list local interfaces

* respond dynamically to network/interface changes

== endpoint list

g_ownIpEndpointList is a u_arraylist_t of CAEndpoint_* in udp_controller

in ocendpoint.c:

typedef struct CAEndpoint_s
{
    CATransportAdapter_t    adapter;    // adapter type
    CATransportFlags_t      flags;      // transport modifiers
    uint16_t                port;       // for IP
    char                    addr[MAX_ADDR_STR_SIZE_CA]; // address for all
    uint32_t                ifindex;    // usually zero for default interface
    char                    remoteId[CA_MAX_IDENTITY_SIZE]; // device ID of remote device
#if defined (ROUTING_GATEWAY) || defined (ROUTING_EP)
    char                    routeData[MAX_ADDR_STR_SIZE_CA]; /**< GatewayId:ClientId of
                                                                    destination. **/
#endif
} CAEndpoint_t;

CATransportFlags_t: enum as bitfield, e.c. CA_SECURE, CA_MULTICAST, CA_IPV4, etc.

initialized by udp_controller::CAIPInitializeQueueHandles

freed by udp_controller::CAIPDeinitializeQueueHandles

managed by udp_controller::CAUpdateStoredIPAddressInfo, which calls
CAGetIPInterfaceInformation, which calls caipserver0::CAIPGetInterfaceInformation(0)
the latter returns a list of CAInterfaceItem_t*
CAGetIPInterfaceInformation turns that list into an ep list

queried by udp_controller::CAIPIsLocalEndpoint, which is called by

cainterfacecontroller::CAIsLocalEndpoint, called ONLY for unicast msgs by

camessagehandler::CADetachSendMessage, called by

    caconnectivitymanager::CASendMessageMultiAdapter
    caconnectivitymanager::CASendRequest
    caconnectivitymanager::CASendResponse

== portability

SIOCGIFCONF won't return IPv6 addrs. Netlink is Linux only.

https://stackoverflow.com/questions/20743709/get-ipv6-addresses-in-linux-using-ioctl :
"Each platform has a different way of getting the IPv6 ones:
Linux, use NETLINK if you're crazy, use getifaddrs if you have a vaguely recent glibc, otherwise read /proc/net/if_inet6 (eg on Android).
Darwin or FreeBSD: use getifaddrs.
Solaris, use SIOCGLIFCONF.
AIX, use SIOCGIFCONF which actually returns IPv4 and IPv6 addresses (because they have an sa_len field in struct sockaddr they can actually support that).
"

Platforms:

    Posix:  shared by all? or just by Linux, BSD, Darwin, Android

    Darwin, Linux, BSD: platform-specific code, e.g. netlink stuff for linux

    Tizen

    Windows


Local network addresses: no really portable method

    BSD:  getifaddrs

    Darwin: BSD getifaddrs - see https://developer.apple.com/library/content/technotes/tn1145/_index.html#//apple_ref/doc/uid/DTS10002984-CH1-SECGETTINGIPLIST[Getting a list of all IP addresses]

    Linux: getifaddrs (not quite same as BSD getifaddrs), netlink

    Android: getifaddrs introduced in 24, otherwise netlink

        android-ifaddrs: https://github.com/morristech/android-ifaddrs


   POSIX: no such API, per https://stackoverflow.com/questions/8645566/is-there-a-posix-compliant-way-of-getting-local-network-ip-address-of-my-compute.

    Windows: GetAdapterAddresses?

why getifaddrs and not netlink? https://stackoverflow.com/questions/579783/how-to-detect-ip-address-change-programmatically-in-linux

getifaddrs manpage: "Support of address families other than IPv4 is available only on kernels that support netlink."

but netlink is Linux-only

Winsock v. POSIX sockets: https://stackoverflow.com/questions/28027937/cross-platform-sockets

Dynamic response to changes:

    Linux:  netlink

    BSD:  ??

    OS X:  System Configuration framework

    Windows: ??

== ip interface

caipinterface.h - misnamed, it's really the caipserver.h

    CAAdapterServerType_t - defined here and in bredr/caedrinterface.h, nfc/canfcinterface.c,
         used in android/caedrserver.c,

    (*CAIPPacketReceivedCallback) - prototyped in caipinterace.h, used in caipserver.c

    (*CAIPErrorHandleCallback) - prototyped in caipinterace.h, used in caipserver.c

    CAIPStartServer - defined caipserver.c, called by caipadapter.c

    CADeInitializeIPGlobals - defined and called inin caipserver.c

    CAIPStopServer - defined in caipserver, used by caipadapter.c

    CAIPStartListenServer - defined by caipserver.c, used by caipserver.c, caipadapter.c,

    CAIPStopListenServer - defined by caipserver.c, used by caipadapter.c

    CAIPSetPacketReceiveCallback - defined by caipserver.c, used by caipadapter.c

    CAIPSetUnicastPort - unused (arduino)

    CAIPSendData - defined in caipserver.c, used by caipadapter.c

    CAIPIsConnected - unused

    CAIPPullData - defined in caipserver.c, used by caipadapter.c

    CAGetPollingInterval - defined in platform caipnwmonitor.c, called by caipserver.c

    CAWakeUpForChange - defined in caipserver.c, not used

    CAIPSetErrorHandler - defined in caipserver.c, used by caipadapter.c


CAProcessNewInterface - misnamed, really means AddIfToMulticastGroups, defined and used in caipserver.c


=== initialization

[source,]
----
OCInitializeInternal(mode, TransportFlags, OCTransportFlags, OCTransportAdapter/type)
=> InitializeScheduleResourceList
=> CAInitialize((CATransportAdapter_t)transportType)
=> OCSelectNetwork(transportType)
=> CARegisterNetworkMonitorHandler
=> client: CARegisterHandler, CAStartDiscoveryServer
=> server: SRMRegisterHandler, CAStartListeningServer
=> both:  SRMRegisterHandler, CAStartListeningServer, CAStartDiscoveryServer
=> not client: initResources
----

=== network monitoring


[source,]
----
OCInitializeInternal passes default handlers:
=> CARegisterNetworkMonitorHandler (comm/util/cautilinterface.c) # 1-line wrapper
==> CASetNetworkMonitorCallbacks (comm/util/cautilinterface.c) # 1-line wrapper
===> AddNetworkStateChangedCallback (cainterfacecontroller.c)

handlers:
OCDefaultAdapterStateChangedHandler (ocstack.c) - sends presence notification
OCDefaultConnectionStateChangedHandler (ocstack.c)
----

AddNetworkStateChangedCallback adds the CB to global handlers list:
g_networkChangeCallbackList (cainterfacecontroller.c)

g_networkChangeCallbackList items are used in
CAAdapterChangedCallback, which is called from
udp_status_change_handler (was CAIPAdapterHandler)
which is called from CAIPPassNetworkChangesToTransports

(What counts as "adapter" state change? Adapter means transport)

CAInitializeAdapters (cainterfacecontroller.c), passing CBs to:
=> CAInitializeIP (caipadapter0.c)
        CARegisterCallback (cainterfacecontroller.c)
	    (will be passed ipHandler struct of CBs, uses it to initialize g_adapterHandler)
	CAReceivedPacketCallback (cainterfacecontroller.c)
	CAAdapterChangedCallback (cainterfacecontroller.c)
	CAAdapterErrorHandleCallback (cainterfacecontroller.c)

obsolete:
CAStartIP passes CAIPAdapterHandler to
CAIPStartNetworkMonitor (caipnwmonitor_<platform>.c)
=> CAIPInitializeNetworkMonitorList (caipnwmonitor0.c)
=> CAIPSetNetworkMonitorCallback (caipnwmonitor0.c) arg: CAIPAdapterStateChangeCallback

Monitoring for network changes is conflated with listening for inbound data messages:

[source,]
----
CAIpStartServer (caipserver.c/) # adds CAReceiveHandler to threadpool
=> cCAReceiveHandler (caipserver.c) # while (!caglobals.ip.terminate) { CAFindReadyMessage(); }
==> CAFindReadyMessage (caipserver_<platform>.c) #
===> CASelectReturned (caipserver_<platform>.c) # loops, recving msgs
        for netlinkFd events, we know sth has changed, so:
            => CAFindInterfaceChange  // use netlink to get RTM_DELADDR, RTM_NEWADDR
                foreach RTM_NEWADDR: we have its index, so:
		    => caipnwmonitor.c/CAIPGetInterfaceInformation(idx) (complicated, see below)
	foreach found interface call caipserver/CAProcessNewInterface to add it to multicast group
----

how is this related to the network monitor callbacks? CAAdapterChangedCallback, etc.




=== servers

We have:

Services are organized in a struct which is initialized in `caipadapter0.c::CAInitializeIP`:

[source,]
----
    static const CAConnectivityHandler_t ipHandler =
        {
            .startAdapter = CAStartIP,
            .stopAdapter = CAStopIP,
            .startListenServer = CAStartIPListeningServer,
            .stopListenServer = CAStopIPListeningServer,
            .startDiscoveryServer = CAStartIPDiscoveryServer,
            .sendData = CASendIPUnicastData,
            .sendDataToAll = CASendIPMulticastData,
            .GetnetInfo = CAGetIPInterfaceInformation,
            .readData = CAReadIPData,
            .terminate = CATerminateIP,
            .cType = CA_ADAPTER_IP
        };
----

[source,]
----
OCInitializeInternal (ocstack.c)
=> OCSelectNetwork (ocstack.c)
==> CASelectNetwork (connectivitymanager.c)
===> CAAddNetworkType (canetworkconfigurator.c) for each nw
====> CAStartAdapter (cainterfacecontroller.c)
=====> CAStartIP (caipadapter0.c) == g_adapterHandler[index].startAdapter() (cainterfacecontroller.c)
======> CAInitializeIPGlobals (caipadapter0)
======> CAIPStartNetworkMonitor (caipnwmonitor_<platform>.c)
=======> CAIPInitializeNetworkMonitorList (caipnwmonitor0.c)
=======> CAIPSetNetworkMonitorCallback (caipnwmonitor0.c)
======> CAIPInitializeQueueHandles (caipadapter0)
======> CAQueueingThreadStart(g_sendQueueHandle) (comm/caqueueingthread.c)
======> CAIPStartServer (caipserver0.c)
=======> create sockets
=======> CAInitializeFastShutdownMechanism
=======> CARegisterForAddressChanges (platform-specific nw status monitoring)
=======> CAIPStartListenServer (caipserver0.c)
========> (see above; CAIPStartListenServer is called twice during initialization)
=======> ca_thread_pool_add_task(threadPool, CAReceiveHandler, NULL);
----


[source,]
----
OCInitializeInternal (ocf/ocstack.c)
=>CAStartDiscoveryServer (comm/caconnectivitymanager.c)
==> CAStartDiscoveryServerAdapters (comm/cainterfacecontroller.c) uses ipHandler above to call:
===> CAGetSelectedNetworkList (comm/canetworkconfigurator.c); for each nw:
===> CAStartIPDiscoveryServer (caipadapter0.c) # one-line wrapper around call to:
====> CAStartIPListeningServer (caipadapter0.c) # only calls:
=====> CAIPStartListenServer (caipadapter0.c)
======> CAIPGetInterfaceInformation(0)
======> applyMulticastToInterface[46] (caipserver0.c) for IFs returned by CAIPGetInterfaceInformation
========> setsockopt on caglobals.ip.m[46]s?.fd with IP_ADD_MEMBERSHIP (4) or IPV6_JOIN_GROUP (6)
----

NOTE: CAStartIPDiscoveryServer and CAStartIPListeningServer are otiose
and can be eliminated; CAStartDiscoveryServerAdapters cann call
CAIPStartListenServer (which should be renamed to e.g. CAStartIPDiscoveryListener) directly.

CAReceiveHandler == callback that loops calling CAFindReadyMessage


 ipHandler.startAdapter from
 (called by caipadapter.c/CAStartIP()
caipserver.c/CAIPStartServer

== network monitor

caipnwmonitor is misnamed. it's really an IP interface manager. This
involves two tasks:

* construct a global list of ifs
* respond dynamically to changes in if status (up/down)

Terminology problems: "interface" & "address", "adapter". One nw
interface may have multiple addresses. Interface =? adapter?

caipnwmonitor.h/CAInterface_t: name, index, flags, family, addr
(string). The comments say this is misnamed since one if could have
multiple addresses. E.g. interface "en1" could have IPv4 and IPv6
addresses. Name/index pairs are unique - one per interface. The
relation between IP interface (name/index) and ifaddrs is one to many.

CAInterface_t is an IP level abstraction. It does not know about transport (UDP/TCP).

CAGetIPInterfaceInformation calls CAIPGetInterfaceInformation(0) to
get a list of CAInterface_t items, then creates Endpoint list.  The
iflist is destroyed.

CAIPGetInterfaceInformation(ifindex), where 0 means all: calls
getifaddrs, then iterates over the ifaddrs till it finds the desired
index.


CASelectReturn calls CAFindInterfaceChange, then for each IF calls
CAProcessNewInterface which adds IFs to multicast groups

CAFindInterfaceChange: for deletions, calls CARemoveFromAddressList(ifiIndex) and CAIPPassNetworkChangesToTransports(CA_INTERFACE_DOWN)

for additions: iflist = CAIPGetInterfaceInformation(ifiIndex) which calls getifaddrs etc and ends up calling CANewInterfaceItem, CAAddToNetworkAddressList, and CAIPPassNetworkChangesToTransports. the latter calls udp_status_change_handler(CA_ADAPTER_IP, status), then CALogAdapterStateInfo(CA_ADAPTER_IP, status);

udp_status_change_handler calls CAUpdateStoredIPAddressInfo then CAAdapterChangedCallback

CAUpdateStoredIPAddressInfo calls CAGetIPInterfaceInformation if IF_UP, maintains g_ownIpEndpointList

CAGetIPInterfaceInformation calls CAIPGetInterfaceInformation(0), then creates eps

so an addition ends up causing a reload of everything (CAIPGetInterfaceInformation(0))

CAAdapterChangedCallback calls CADefault...


Related data structs:

cacommon.h/CAEndpoint_t - transport adapter and flags, port, addr
(string), ifindex, remoteid cacommon.h/CATransportAdapter_t - enum,
CA_ADAPTER_IP (meaning UDP?), CA_ADAPTER_TCP, etc.
cacommon.h/CATransportFlags_t - enum, secure, multicast, scope, ip
version

Network IP if manager API:
caipnwmonitor.c/g_netInterfaceList  = list of CAInterface_t (u_array_list_t*)
CAIPInitializeNetworkMonitorList    = create_global_iflist
CAIPDestroyNetworkMonitorList       = destroy_global_iflist
CAAddNetworkMonitorList             = add_if_to_global_iflist (CAInterface_t)
CARemoveNetworkMonitorList          = remove_if_from_global_iflist
CACmpNetworkList(uint32_t ifiindex) = if_is_on_global_iflist (bool)

NB: as far as I can tell, g_netInterfaceList is not actually used for
anything. Clients always use the list of CAInterface_t dynamically
created and returned by CAIPGetInterfaceInformation.

The global if list is populated by CAIPGetInterfaceInformation.

At startup, CAIPStartListenServer calls
CAIPGetInterfaceInformation(0), which calls getifaddrs and then
iterates over all ifaddrs:

* converts each discovered ifaddrs to CAInterface_t and passes it to CAAddNetworkMonitorList
* makes a copy of that CAInterface_t and adds it to a list of CAInterface_t (u_arraylist_t*)
* returns the u_arraylist_t*

When if status changes, CAIPGetInterfaceInformation is called with the
index of the changed if.  E.g. CAFindInterfaceChange queries the
netlink socket to get the indices of changed interfaces. It then calls
CAIPGetInterfaceInformation, passing the index of the changed if,
which calls CAAddNetworkMonitorList (for RTM_NEWADDR) or
CARemoveNetworkMonitorList (for RTMM_DELADDR).

The netlink socket is set up in CARegisterForAddressChanges <= CAIPStartServer <= ... <= OCInit

CAIPGetInterfaceInformation(0) (i.e. get all ifs) is called by:

* caipserver.c/CAIPStartListenServer - called by:
<== caipadapter.c/CAStartIPListeningServer (called by caipadapter.c/CAStartIPDiscoveryServer, from ipHandler.startDiscoveryServer set in CAInitializeIP, .startDiscoveryServer called by cainterfacecontroller.c/CAStartDiscoveryServerAdapters, by caconnectivitymanager.c/CAStartDiscoveryServer, by ocstack.c/OCInitializeInternal)
<== caipserver.c/CAIPStartServer (called by caipadapter.c/CAStartIP(), which is also ipHandler.startAdapter from CAInitializeIP, which is called by cainterfacecontroller.c/CAStartAdapter, called by canetworkconfigurator.c/CAAddNetworkType, called by connectivitymanager.c/CASelectNetwork,called by ocstack.c/OCSelectNetwork, called by ocstack.c/OCInitializeInternal, by OCInit2, by OCInit1, by OCInit, by application)
* caipserver.c/CAIPSendData (for multicast msgs)
* caipserver.c/CAGetIPInterfaceInformation(/CAEndpoint_t **info, size_t *size)
<== called by caipadapter.c/CAUpdateStoredIPAddressInfo(CANetworkStatus_t status)
<==== called by CAIPAdapterHandler(CATransportAdapter_t adapter, CANetworkStatus_t status)
<====== called by CAStartIP()
<== stored as CAConnectivityHandler_t ipHandler.GetnetInfo from CAInitializeIP
<==== called by cainterfacecontroller.c/CAGetNetworkInfo (output arg: CAEndpoint_t**)
<====== called by canetworkconfigurator.c/CAGetNetworkInformationInternal
<======== called by caconnectivitymanager.c/CAGetNetworkInformation
<========== called by e.g. ocresource.c/HandleVirtualResource, etc.

Note the redundancy. We call CAIPGetInterfaceInformation multiple times at startup
(OCInitializeInternal), whenever a multicast msg is sent, and when


On all platforms we have a set of 8 comm sockets (ipv4/ipv6,
unicast/multicast, secure/insecure).

We also have two "meta" sockets, one for ipaddr change event
detection, one to signal shutdown to threads. These are
platform-specific:

    ip addr changes:

       Linux uses netlink socket
       OS X - sys config framework?
       	   https://developer.apple.com/library/content/technotes/tn1145/_index.html#//apple_ref/doc/uid/DTS10002984-CH1-SECGETTINGIPLIST
	   https://stackoverflow.com/questions/3613521/udp-socket-network-disconnect-behavior-on-windows-linux-mac
       BSD - ioctl(SIOCGIFCONF)?
       Windows uses WSAEVENT

    shutdown event signaling:

        Linux, BSD, Darwin - pipe
	Windows uses WSAEVENT

caglobals.ip.shutdownFds -> shutdownPipe
shutdownFds[0] ->  shutdownPipe[READPORT]
shutdownFds[1] ->  shutdownPipe[WRITEPORT]

one header caipnwmonitor.h, platform-specific implementations

caipnwmonitor.h/CAIPCBData_t holds CATransportAdapter_t * and CAIPAdapterStateChangeCallback *


caipadapter.c/CAStartIP
=> caipnwmonitor.c/CAIPStartNetworkMonitor(cb, adapter)
===> caipnwmonitor.c/CAIPInitializeNetworkMonitorList() - creates mutex, global if list
===> CAIPSetNetworkMonitorCallback(cb, adapter)
       creates CAIPCBData_t* for cb/adapter, adds to g_adapterCallbackList

https://jira.iotivity.org/browse/IOT-437


caipserver.c/CAIpStartServer // adds CAReceiveHandler to threadpool

caipserver./cCAReceiveHandler  // while (!caglobals.ip.terminate) { CAFindReadyMessage(); }

caipserver.c/CAFindReadyMessage // calls select on the set of global fds, CASelectReturned on ready fds

caipserver.c/CASelectReturned // loops, recving msgs, until all recvd or caglobals.ip.terminate
        for netlinkFd events, we know sth has changed, so:
            => CAFindInterfaceChange  // use netlink to get RTM_DELADDR, RTM_NEWADDR
                foreach RTM_NEWADDR: we have its index, so:
		    => caipnwmonitor.c/CAIPGetInterfaceInformation(idx) (complicated, see below)
	foreach found interface call caipserver/CAProcessNewInterface to add it to multicast group

%%%%%%%%%%%%%%%%
caipnwmonitor.c/CAIPGetInterfaceInformation for a desired index

input arg is 0, or if index obtained from netlink RTM_NEWADDR if called from CAFindInterfaceChange

Called by two kinds of routines

    * those that need to process all ifs, e.g. CAIPStartListenServer adds them all to multicast group.

    * those that need only on if. e.g. called by nwmonitor on
 detection of nw changes, for the side effect of adding newly found
 ifs to nw monitoring list (and ignoring the returnd iflist). iow this
 is a very badly designed routine.

Hidden semantics: passing 0 as desired index means return all ifs,
otherwise just the one.

what does "interface information" mean, exactly?

create an u_arraylist_t * iflist to hold ifs

    call getifaddrs to get ifaddrs *ifp  (NB: each if has an (one?) address and an (one?) index)

    iterate over if addresses to find matching index:

    once we find the if by index, OR if desired index is 0:

        iterate over the iflist to see if if already added, matching index and family

	  one if has one name/index, but may have multiple addrs. we only store one CAInterfaceItem per name/index, apparently. seems a bug.

	if not: create a CAInterface_t for it, add to iflist
	if not already on the NetworkList, then
	    caipnwmonitor/CANewInterfaceItem
	        this creates a new  CAInterface_t* from the one we just made, why? because iflist owns that one
	    CAAddNetworkMonitorList, CAIPPassNetworkChangesToAdapter

CAIPPassNetworkChangesToAdapter takes one arg, if_up or down; how does
it know which adapter? it doesn't, it iterates over all adapter cbs
and passes the status (IF_UP/IF_DOWN) to each. bug?
