# //******************************************************************
# //
# // Copyright 2015 Intel Mobile Communications GmbH All Rights Reserved.
# //
# //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# //
# // Licensed under the Apache License, Version 2.0 (the "License");
# // you may not use this file except in compliance with the License.
# // You may obtain a copy of the License at
# //
# //      http://www.apache.org/licenses/LICENSE-2.0
# //
# // Unless required by applicable law or agreed to in writing, software
# // distributed under the License is distributed on an "AS IS" BASIS,
# // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# // See the License for the specific language governing permissions and
# // limitations under the License.
# //
# //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Import('test_env')
import os
import os.path
import build.utils

src_dir = test_env.get('SRC_DIR')
target_os = test_env.get('TARGET_OS')

######################################################################
# Build flags
######################################################################
home = os.environ['HOME']

test_env.PrependUnique(CPPPATH = [
		'#resource/c_common',
		'#resource/csdk/security',
		'#resource/csdk/security/ocsecurity',  #FIXME this is private
		'#resource/csdk/security/provisioning/include',
 		'#resource/csdk/connectivity/api',
 		'#resource/csdk/connectivity/inc',
		'#resource/csdk/connectivity/lib/libcoap-4.1.1',
		Dir('.').abspath + '../include',
		'#resource/csdk/logger',
		'#resource/csdk/stack',
		'#resource/csdk/cbor/',
                '#resource/csdk/cjson/',
                '#resource/csdk/timer'
		])
#		'../../../oc_logger/include',
#		'../../stack/internal',
#		'../include/internal',
#		'../../connectivity/external/inc',

test_env.AppendUnique(LIBPATH = [test_env.get('BUILD_DIR')])
test_env.AppendUnique(LIBPATH = [test_env.get('BUILD_DIR')])

test_env.PrependUnique(LIBS = ['ocsrm'
			         ,'octbstack'
				 ,'connectivity_abstraction'
				 ,'coap'])
				 # ,'oc_logger'


# if target_os != 'darwin':
#         test_env.PrependUnique(LIBS = ['uuid'])


if test_env.get('SECURED') == '1':
    test_env.AppendUnique(LIBS = ['tinydtls'])

if test_env.get('LOGGING') == '1':
	test_env.AppendUnique(CPPDEFINES = ['TB_LOG'])

if target_os == 'windows':
	test_env.AppendUnique(LINKFLAGS = ['/subsystem:CONSOLE'])
	test_env.AppendUnique(LIBS = ['advapi32', 'kernel32', 'ws2_32', 'iphlpapi'])
# else:
# 	# TODO: Implement feature check.
# 	test_env.AppendUnique(CPPDEFINES = ['HAVE_LOCALTIME_R'])

######################################################################
# Source files and Targets
######################################################################
securitytest = test_env.Program('securitytest', ['aclresourcetest.cpp',
                                            'amaclresourcetest.cpp',
                                            'pstatresource.cpp',
                                            'doxmresource.cpp',
                                            'policyengine.cpp',
                                            'securityresourcemanager.cpp',
                                            'credentialresource.cpp',
                                            'srmutility.cpp',
                                            'iotvticalendartest.cpp',
                                            'base64tests.cpp',
                                            'svcresourcetest.cpp',
                                            'srmtestcommon.cpp',
                                            'directpairingtest.cpp',
                                            'crlresourcetest.cpp'])
                                            # os.path.join(src_dir, 'resource', 'csdk', 'timer', 'timer.c')])

Alias("test", [securitytest])

securitytest_src_dir = os.path.join(src_dir,
                                    'resource', 'csdk', 'security', 'unittest') + os.sep
# securitytest_build_dir = os.path.join(test_env.get('BUILD_DIR'),
#                                       'resource', 'csdk', 'security', 'unittest') + os.sep
securitytest_build_dir = os.path.join(test_env.get('INSTALL_SYSROOT') + '/bin')
print "SECTEST BUILD DIR:", securitytest_build_dir

test_env.AppendUnique(CPPDEFINES = ['SECURITY_BUILD_UNITTEST_DIR='+securitytest_build_dir.encode('string_escape')])

test_env.Alias("install", test_env.Install( securitytest_build_dir,
                                            securitytest_src_dir + 'oic_unittest.json'))
test_env.Alias("install", test_env.Install( securitytest_build_dir,
                                            securitytest_src_dir + 'oic_unittest_acl1.json'))
test_env.Alias("install", test_env.Install( securitytest_build_dir,
                                            securitytest_src_dir + 'oic_unittest_default_acl.json'))
test_env.Alias("install", test_env.Install( securitytest_build_dir,
                                            securitytest_src_dir + 'oic_svr_db.json'))

test_env.Alias("install", test_env.Install( securitytest_build_dir,
                                            securitytest_src_dir + 'oic_unittest.dat'))
test_env.Alias("install", test_env.Install( securitytest_build_dir,
                                            securitytest_src_dir + 'oic_unittest_acl1.dat'))
test_env.Alias("install", test_env.Install( securitytest_build_dir,
                                            securitytest_src_dir + 'oic_unittest_default_acl.dat'))
test_env.Alias("install", test_env.Install( securitytest_build_dir,
                                            securitytest_src_dir + 'oic_svr_db_prov.dat'))
test_env.Alias("install", test_env.Install( securitytest_build_dir,
                                            securitytest_src_dir + 'oic_svr_db.dat'))

#test_env.Install(os.path.join(test_env.get('INSTALL_SYSROOT'), 'test'), securitytest)
build.utils.install_bin(test_env, securitytest, 'securitytest')

# if test_env.get('WITH_VALGRIND'):
#         valgrind_xml = 'ut'
# else:
#         valgrind_xml = ''

# import test_utils
# test_utils.run_test(test_env,
#                          valgrind_xml,
#                          'resource/csdk/security/unittest/unittest')
